language: csharp
mono: none
dotnet: 2.1
install:
- dotnet restore
script:
- dotnet build
before_install:
- openssl aes-256-cbc -K $encrypted_297cfd2d2aa9_key -iv $encrypted_297cfd2d2aa9_iv
  -in ssh.enc -out ~\/dev/conqsolid/ssh -d
